### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by FlatronSamatron** [FlatronSamatron/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by necket** [comment]
Entrepreneur (mainly in real estate), showman and TV presenter. Time Magazine's Person of the Year Donald Trump was president of the Trump Organization, a construction conglomerate and founder of Trump Entertainment Resorts, a gambling and hospitality company. In 1996-2015, he was the owner of the Miss Universe beauty pageant. 
He has appeared as a cameo in a number of films and television series. In addition, Donald Trump served as an executive producer and hosted the reality show The Candidate on NBC for 14 seasons (2004-2015). Since the 1988 presidential election, Donald Trump has been viewed as a potential candidate for the presidency of the United States in almost every election. In October 1999, he declared himself a potential candidate from the Reform Party for the presidential nomination in the United States, but on February 14, 2000, withdrew his candidacy from the elections.

Announced his entry into the fight for the post of the next US President on June 16, 2015. " In May 2016, having outstripped all rivals in the primaries, he actually guaranteed himself the nomination of a single candidate from the Republican Party.

**Comment by necket** [comment]
Entrepreneur (mainly in real estate), showman and TV presenter. Time Magazine's Person of the Year Donald Trump was president of the Trump Organization, a construction conglomerate and founder of Trump Entertainment Resorts, a gambling and hospitality company. In 1996-2015, he was the owner of the Miss Universe beauty pageant. 
He has appeared as a cameo in a number of films and television series. In addition, Donald Trump served as an executive producer and hosted the reality show The Candidate on NBC for 14 seasons (2004-2015). Since the 1988 presidential election, Donald Trump has been viewed as a potential candidate for the presidency of the United States in almost every election. In October 1999, he declared himself a potential candidate from the Reform Party for the presidential nomination in the United States, but on February 14, 2000, withdrew his candidacy from the elections.

Announced his entry into the fight for the post of the next US President on June 16, 2015. " In May 2016, having outstripped all rivals in the primaries, he actually guaranteed himself the nomination of a single candidate from the Republican Party.
